### ISSUE TITLE
Quilt installer 

### ISSUE THREAD

**Issue by JulianVennen** [QuiltMC/quilt-installer#42]
Running Quilt installer 0.8.1 with the command `java -jar quilt-installer-0.8.1.jar install server 1.20.1 --download-server` results in the following error:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(String[])void to ()void
	at org.quiltmc.installer.Main.main(Main.java:60)
Caused by: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(String[])void to ()void
	at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:884)
	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:869)
	at java.base/java.lang.invoke.Invokers.checkGenericType(Invokers.java:542)
	at org.quiltmc.installer.Main.main(Main.java:33)
```

**Comment by JulianVennen** [comment]
For some reason, 0.8.2 doesn't appear in the quilt meta API yet: https://meta.quiltmc.org/v3/versions/installer
Is there just a very long cache duration on that, or is this intended?

**Comment by JulianVennen** [comment]
0.8.2 is available on the meta server now and the issue appears to be fixed
